env:
  browser: true
  es2021: true
extends: ['eslint:recommended', 'plugin:react/recommended', 'prettier']
plugins: ['react', 'prettier']
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    'no-console': 'off',
    'prettier/prettier': 'error',
    'import/extensions': 'off',
    'operator-linebreak': ['error', 'after'],
  }
